### ISSUE TITLE
Compatibility problems with externalsystem api in Idea 15 / 16

### ISSUE THREAD

**Issue by nicity** [atsky/haskell-idea-plugin#125]
com/intellij/openapi/externalSystem/service/project/PlatformFacade

java.lang.NoClassDefFoundError: com/intellij/openapi/externalSystem/service/project/PlatformFacade
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter$2.run(ConstructorInjectionComponentAdapter.java:146)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getConstructors(ConstructorInjectionComponentAdapter.java:144)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getSortedMatchingConstructors(ConstructorInjectionComponentAdapter.java:126)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getGreediestSatisfiableConstructor(ConstructorInjectionComponentAdapter.java:70)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:210)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:232)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:41)
	at org.jetbrains.cabal.settings.CabalLocalSettings.getInstance(Unknown Source)
	at org.jetbrains.cabal.CabalManager$getLocalSettingsProvider$1.fun(CabalManager.kt:39)
	at org.jetbrains.cabal.CabalManager$getLocalSettingsProvider$1.fun(CabalManager.kt:27)
	at com.intellij.openapi.externalSystem.service.project.manage.ExternalProjectsDataStorage.mergeLocalSettings(ExternalProjectsDataStorage.java:256)
	at com.intellij.openapi.externalSystem.service.project.manage.ExternalProjectsDataStorage.load(ExternalProjectsDataStorage.java:100)
	at com.intellij.openapi.externalSystem.service.project.manage.ExternalProjectsManager.init(ExternalProjectsManager.java:123)
	at com.intellij.openapi.externalSystem.service.ExternalSystemStartupActivity.runActivity(ExternalSystemStartupActivity.java:77)
	at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:150)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:348)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$700(StartupManagerImpl.java:61)
	at com.intellij.ide.startup.impl.StartupManagerImpl$3.run(StartupManagerImpl.java:168)
	at com.intellij.openapi.project.DumbServiceImpl.notifyUpdateFinished(DumbServiceImpl.java:326)
	at com.intellij.openapi.project.DumbServiceImpl.access$1300(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$4.run(DumbServiceImpl.java:304)
	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:283)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:302)
	at com.intellij.openapi.project.DumbServiceImpl.access$1100(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$12.run(DumbServiceImpl.java:511)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.externalSystem.service.project.PlatformFacade PluginClassLoader[Haskell, 0.5.2]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 53 more

**Comment by Cmdv** [comment]
Unfortunately I'm having the same issues, I assume this plugin in potentially using an older version of Java, is there a chance of potentially looking into this? thank you

**Comment by htbkoo** [comment]
Me too, similar issue encountered for IntelliJ IDEA 2017.2.5
> INFO - llij.ide.plugins.PluginManager - Plugin 'Haskell' can't be loaded because: This plugin version was marked as incompatible 

Would be great if there is a chance that this is fixed - and thanks for maintaining the plugin. :)
