### ISSUE TITLE
Write access is allowed from write-safe contexts only

### ISSUE THREAD

**Issue by nicity** [atsky/haskell-idea-plugin#132]
IntelliJ IDEA Community 2016.3 EAP build 163.6512
<< Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
  known modalities={ModalityState:com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog0,585,511,741x108,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Open Project,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=,rootPaneCheckingEnabled=true]=true, ModalityState.NON_MODAL=true, ModalityState:Loading Project 847545838: running=false; canceled=false=true, ModalityState:Loading Project 186731146: running=false; canceled=false=true}

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:246)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:296)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:288)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator$$anonfun$saveAllFiles$1.apply$mcV$sp(HaskellExternalAnnotator.scala:58)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator$$anonfun$saveAllFiles$1.apply(HaskellExternalAnnotator.scala:58)
	at com.haskforce.highlighting.annotation.external.HaskellExternalAnnotator$$anonfun$saveAllFiles$1.apply(HaskellExternalAnnotator.scala:58)
	at com.haskforce.Implicits$Fun0$$anon$3.run(Implicits.scala:16)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:170)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:421)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:405)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by nicity** [comment]
https://youtrack.jetbrains.com/issue/IDEA-169801
