### ISSUE TITLE
Cabal

### ISSUE THREAD

**Issue by spitfiredd** [Atsky/haskell-idea-plugin#20]
How do you get cabal to show up on the side, like in the screenshot? I went to View -> Tools Window -> Cabal and the screen opened on the right hand side.  However I got an error?

I did install a new version of cabal after I installed the plugin, should I uninstall the plugin and then re-install?

**Comment by razvan-panda** [comment]
@Atsky Having same problem with version 0.5.1 of the plugin and cabal 1.22 / ghc-mod built from master https://github.com/kazu-yamamoto/ghc-mod/commit/bfa0b965ee3497f5f41d261072dc6bae0af00a06

Getting an `StringIndexOutOfBoundsException: String index out of range: -1` on each automatic run of GhcMod.

**Comment by Atsky** [comment]
@razvan-panda, can you provide full stacktrace?

**Comment by razvan-panda** [comment]
@Atsky Sure:

    String index out of range: -1
    java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.<init>(String.java:195)
        at org.jetbrains.haskell.external.GhcModi.runCommand(GhcModi.kt:116)
        at org.jetbrains.haskell.external.HaskellExternalAnnotator.getResultFromGhcModi(HaskellExternalAnnotator.kt:95)
        at org.jetbrains.haskell.external.HaskellExternalAnnotator.doAnnotate(HaskellExternalAnnotator.kt:164)
        at org.jetbrains.haskell.external.HaskellExternalAnnotator.doAnnotate(HaskellExternalAnnotator.kt:32)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:183)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:45)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:125)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
        at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
        at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
        at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
        at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
        at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
        at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
        at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)


Thanks for the quick reply

**Comment by Atsky** [comment]
@razvan-panda, this is new issue #98
