### ISSUE TITLE
0.4.1 beta wont start haskell repl

### ISSUE THREAD

**Issue by sammerry** [Atsky/haskell-idea-plugin#74]
I get this error every time i open the haskell repl drop down menu

![screen shot 2015-01-03 at 4 55 05 pm](https://cloud.githubusercontent.com/assets/723565/5604307/669c178a-9369-11e4-8adf-eefaf6fe6ef9.png)

```
NoClassDefFoundError: update failed for AnAction with ID=ideah.repl.actions.RunHaskellConsoleAction: com/intellij/openapi/actionSystem/DataKeys
```

```
update failed for AnAction with ID=ideah.repl.actions.RunHaskellConsoleAction: com/intellij/openapi/actionSystem/DataKeys
java.lang.NoClassDefFoundError: com/intellij/openapi/actionSystem/DataKeys
	at org.jetbrains.haskell.repl.actions.RunHaskellConsoleAction.getModule(Unknown Source)
	at org.jetbrains.haskell.repl.actions.RunHaskellConsoleAction.update(Unknown Source)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:113)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:187)
	at com.intellij.openapi.actionSystem.impl.Utils.updateGroupChild(Utils.java:264)
	at com.intellij.openapi.actionSystem.impl.Utils.hasChildrenWithState(Utils.java:238)
	at com.intellij.openapi.actionSystem.impl.Utils.hasEnabledChildren(Utils.java:208)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:146)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:85)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:279)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.access$400(ActionMenu.java:41)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:235)
	at javax.swing.JMenu.fireMenuSelected(JMenu.java:1028)
	at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1107)
	at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:333)
	at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:215)
	at javax.swing.JMenu.setSelected(JMenu.java:294)
	at com.apple.laf.ScreenMenu$1.run(ScreenMenu.java:117)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
	at apple.awt.CToolkit$CPeerEvent.dispatch(CToolkit.java:1221)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.actionSystem.DataKeys PluginClassLoader[Haskell, 0.4.1 Beta]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 37 more



java.lang.NoClassDefFoundError: com/intellij/openapi/actionSystem/DataKeys
	at org.jetbrains.haskell.repl.actions.RunHaskellConsoleAction.getModule(Unknown Source)
	at org.jetbrains.haskell.repl.actions.RunHaskellConsoleAction.update(Unknown Source)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:113)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:187)
	at com.intellij.openapi.actionSystem.impl.Utils.updateGroupChild(Utils.java:264)
	at com.intellij.openapi.actionSystem.impl.Utils.hasChildrenWithState(Utils.java:238)
	at com.intellij.openapi.actionSystem.impl.Utils.hasEnabledChildren(Utils.java:208)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:146)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:85)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:279)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.access$400(ActionMenu.java:41)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:235)
	at javax.swing.JMenu.fireMenuSelected(JMenu.java:1028)
	at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1107)
	at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:333)
	at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:215)
	at javax.swing.JMenu.setSelected(JMenu.java:294)
	at com.apple.laf.ScreenMenu$1.run(ScreenMenu.java:117)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
	at apple.awt.CToolkit$CPeerEvent.dispatch(CToolkit.java:1221)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by sammerry** [comment]
Plugin version 0.4.1
PyCharm version 3.4.1

**Comment by Atsky** [comment]
Fixed
